### ISSUE TITLE
About the data generation

### ISSUE THREAD

**Issue by ZhenChen008** [lucaswo/learned-selection-strategy#1]
Hello, I've read this article and found it to be excellent work.👍
 I'm wondering if the **data generation method** can be directly applied to the selection of floating-point compression algorithms?

**Comment by lucaswo** [comment]
Hi, yes this would work. You just need to adapt the [sample_bw_hist](https://github.com/lucaswo/learned-selection-strategy/blob/eca8500d2f48968614256b58befd72c4c65b14fe/util/generator.py#L85) function to generate [floats instead of integers](https://github.com/lucaswo/learned-selection-strategy/blob/eca8500d2f48968614256b58befd72c4c65b14fe/util/generator.py#L102). Note that you would also need to adapt the calculation of the upper and lower bucket limits to fit your needs.
